"""
Adaptive-exercise service.

Ties the evidence-aware assessment (assessment.py) to exercise selection
(content.py + the DB exercise bank) so the two steps are visible in one place:

    1. assess          -> evidence-aware level + weak/unknown phonemes
    2. choose_exercise -> one practice sentence targeting those phonemes,
                          from the tagged bank (retrieval) or, if the bank has
                          no good match, generated by an LLM and verified with
                          the SAME G2P pipeline before it is accepted.

The same ``choose_exercise`` is used by both the ``/exercise`` service
endpoint and the main ``/practice/next`` adaptive flow, so there is one
implementation of the selection policy.

``g2p_convert`` / ``ipa_to_tokens`` are passed in by the caller so this module
never imports app.py (no circular import) and verification always uses the
exact G2P path the learner is later scored against.
"""

from __future__ import annotations

import math
from datetime import datetime, timezone
from typing import Any, Callable, Dict, List, Optional

from src.core.scoring import assessment as assessment_mod
from src.core.g2p import content
from src.core.persistence import db
from src.core.scoring import mastery
from src.core.shared.app_datetime import parse_db_datetime
from src.core.g2p.phoneme_vectors_professional import canonicalize_phoneme


def _stats_from_rows(rows) -> Dict[str, "mastery.PhonemeStat"]:
    stats: Dict[str, mastery.PhonemeStat] = {}
    for row in rows:
        stats[row["phoneme"]] = mastery.PhonemeStat(
            alpha=row["alpha"],
            beta=row["beta"],
            independent_attempts=row["attempts_count"],
            occurrence_count=(row["occurrence_count"] if "occurrence_count" in row.keys() else 0),
            last_practiced_at=parse_db_datetime(row["last_practiced_at"]),
        )
    return stats


def load_profile_stats(user_id: int) -> Dict[str, "mastery.PhonemeStat"]:
    return _stats_from_rows(db.get_all_phoneme_states(user_id))


def assess_profile(user_id: int, now: Optional[datetime] = None) -> Dict[str, Any]:
    """Authoritative evidence-aware assessment for a saved profile."""
    now = now or datetime.now(timezone.utc)
    stats = load_profile_stats(user_id)
    context_stats = db.get_phoneme_context_stats(user_id)
    recording_count = db.get_trusted_recording_count(user_id)
    effective_recording_count = db.get_effective_recording_count(user_id)
    utterance_state = db.get_utterance_epenthesis_state(user_id)
    return assessment_mod.assess_user_level(
        stats,
        context_stats,
        recording_count,
        now=now,
        effective_recording_count=effective_recording_count,
        utterance_state=utterance_state,
    )


def _confusion_hint_for(target: Optional[str], confusion_pairs: List[Dict[str, Any]]) -> Optional[str]:
    if not target:
        return None
    confusion = assessment_mod.main_confusion_for(target, confusion_pairs)
    if confusion is None:
        return None
    return f"{confusion['expected']} vs {confusion['spoken']}"


def _word_count_range_for(exercise_type: str) -> Optional[tuple]:
    """Length band each functional exercise type draws from."""
    if exercise_type == "short_phrase":
        return (1, content.SHORT_PHRASE_MAX_WORDS)
    if exercise_type == "targeted_sentence":
        return (1, content.TARGETED_SENTENCE_MAX_WORDS)
    if exercise_type == "maintenance":
        return (content.MAINTENANCE_MIN_WORDS, content.MAX_WORD_COUNT)
    return None


def choose_exercise(
    targets: List[str],
    overmastered: List[str],
    under_observed: List[str],
    overall_level: Optional[str],
    recently_served_ids: set,
    g2p_convert: Callable[[str], str],
    ipa_to_tokens: Callable[[str], List[str]],
    exercise_type: str = "targeted_sentence",
    top_target: Optional[str] = None,
    confusion_phoneme: Optional[str] = None,
    diagnostic: bool = False,
) -> Dict[str, Any]:
    """Shared, exercise-type-driven selection policy. Returns
    {source_mode, exercise|None, generated|None}.

    ``exercise_type`` actually shapes what is served:
      * minimal_pairs   -> isolated words / minimal pairs (confusion-aware)
      * short_phrase    -> short bank sentences
      * targeted_sentence -> normal targeted sentences
      * maintenance     -> longer / connected-speech sentences
    Retrieval is confusion-aware via ``confusion_phoneme`` (the sound the
    learner substitutes for the target), not only the LLM path.
    """
    target_difficulty = content.difficulty_for_level(overall_level)
    confusion_hint = (
        f"{canonicalize_phoneme(top_target)} vs {canonicalize_phoneme(confusion_phoneme)}"
        if top_target and confusion_phoneme else None
    )
    confusion_phonemes = {confusion_phoneme} if confusion_phoneme else set()

    if diagnostic or not targets:
        chosen = content.pick_diagnostic_sentence(
            db.get_all_sentences(), recently_served_ids, uncovered_phonemes=under_observed
        )
        return {"source_mode": "diagnostic", "exercise": chosen, "generated": None}

    # Low mastery: serve actual isolated words / minimal pairs (contrastive).
    if exercise_type == "minimal_pairs":
        drill = content.make_low_mastery_exercise(
            top_target or targets[0], confusion_phoneme, g2p_convert, ipa_to_tokens
        )
        if drill is not None:
            return {"source_mode": drill["source"], "exercise": None, "generated": drill}

    candidates = db.get_sentences_covering_any(targets)
    best = content.pick_next_sentence(
        candidates,
        targets,
        overmastered_phonemes=overmastered,
        recently_served_ids=recently_served_ids,
        target_difficulty=target_difficulty,
        under_observed_phonemes=under_observed,
        confusion_phonemes=confusion_phonemes,
        word_count_range=_word_count_range_for(exercise_type),
    )

    required_overlap = (len(targets) + 1) // 2
    best_overlap = 0 if best is None else sum(1 for p in targets if p in best["phoneme_counts"])

    generated = None
    source_mode = exercise_type
    if best_overlap < required_overlap:
        generated = content.generate_and_verify_exercise(
            targets, overmastered, g2p_convert, ipa_to_tokens,
            level=overall_level, confusion_hint=confusion_hint,
        )
        if generated is not None:
            source_mode = "generated"

    if generated is not None:
        return {"source_mode": source_mode, "exercise": None, "generated": generated}
    if best is not None:
        return {"source_mode": exercise_type, "exercise": best, "generated": None}

    chosen = content.pick_diagnostic_sentence(
        db.get_all_sentences(), recently_served_ids, uncovered_phonemes=under_observed
    )
    return {"source_mode": "diagnostic", "exercise": chosen, "generated": None}


def generate_exercise(
    metrics: Dict[str, float],
    g2p_convert: Callable[[str], str],
    ipa_to_tokens: Callable[[str], List[str]],
    recently_served_ids: Optional[set] = None,
) -> Dict:
    """Stateless metrics -> assessment + one exercise (the ``/exercise`` POST
    path). Because a raw metrics dict carries no evidence counts, its level is
    always reported as provisional, never established."""
    recently_served_ids = recently_served_ids or set()
    assessment = provisional_assessment_from_metrics(metrics)
    targets = [w["phoneme"] for w in assessment["weak_phonemes"]][: content.MIN_TARGET_REPETITIONS + 1]
    overmastered = assessment["strong_phonemes"]

    top_target = targets[0] if targets else None
    top_mastery = (metrics or {}).get(top_target) if top_target else None
    exercise_type = assessment_mod.exercise_type_for_mastery(top_mastery, is_unknown=not targets)

    result = choose_exercise(
        targets=targets,
        overmastered=overmastered,
        under_observed=assessment["unknown_phonemes"],
        overall_level=assessment["overall_level"],
        recently_served_ids=recently_served_ids,
        g2p_convert=g2p_convert,
        ipa_to_tokens=ipa_to_tokens,
        exercise_type=exercise_type,
        top_target=top_target,
        confusion_phoneme=None,
        diagnostic=not targets,
    )

    exercise = result["exercise"]
    if result["generated"] is not None:
        gen = result["generated"]
        new_id = db.insert_sentence(
            text=gen["text"],
            reference_ipa=gen["reference_ipa"],
            word_count=gen["word_count"],
            level_proxy=gen["level_proxy"],
            phoneme_counts=gen["phoneme_counts"],
            source="llm_generated",
        )
        if new_id is not None:
            gen["id"] = new_id
            exercise = gen
        else:
            existing = db.get_sentence_by_text(gen["text"])
            if existing is not None:
                gen["id"] = existing["id"]
                exercise = gen

    if exercise is None:
        return {
            "assessment": assessment,
            "exercise": None,
            "error": "No exercises available. Run scripts/build_exercise_bank.py to populate the bank.",
        }

    return {
        "assessment": assessment,
        "source_mode": result["source_mode"],
        "target_phonemes": targets,
        "exercise": {
            "sentence_id": exercise["id"],
            "text": exercise["text"],
            "reference_ipa": exercise["reference_ipa"],
        },
    }


def generate_exercise_for_profile(
    user_id: int,
    g2p_convert: Callable[[str], Any],
    ipa_to_tokens: Callable[[str], List[str]],
    recently_served_ids: Optional[set] = None,
    now: Optional[datetime] = None,
) -> Dict[str, Any]:
    """Saved-profile exercise path using the authoritative assessment.

    Unlike the raw metrics API, this keeps posterior intervals, evidence
    eligibility, unknown coverage, quality weights, epenthesis state, and
    confusion history intact.
    """
    now = now or datetime.now(timezone.utc)
    recently_served_ids = recently_served_ids or set()
    assessment = assess_profile(user_id, now=now)
    stats = load_profile_stats(user_id)
    diagnostic = assessment_mod.diagnostic_status(db.get_phoneme_context_stats(user_id))
    targets = [] if diagnostic["in_diagnostic"] else [
        item["phoneme"] for item in assessment["weak_phonemes"]
    ][: content.MIN_TARGET_REPETITIONS + 1]
    overmastered = sorted(mastery.get_overmastered_phonemes(stats, now=now))
    top_target = targets[0] if targets else None
    confusion = assessment_mod.main_confusion_for(
        top_target, db.get_confusion_pairs(user_id)
    ) if top_target else None
    confusion_phoneme = confusion["spoken"] if confusion else None
    top_mastery = mastery.posterior_mean(stats[top_target], now=now) if top_target in stats else None
    exercise_type = (
        "diagnostic"
        if diagnostic["in_diagnostic"]
        else assessment_mod.exercise_type_for_mastery(top_mastery, is_unknown=not targets)
    )

    selection = choose_exercise(
        targets=targets,
        overmastered=overmastered,
        under_observed=diagnostic["uncovered"],
        overall_level=assessment.get("exercise_level", assessment["overall_level"]),
        recently_served_ids=recently_served_ids,
        g2p_convert=g2p_convert,
        ipa_to_tokens=ipa_to_tokens,
        exercise_type=exercise_type,
        top_target=top_target,
        confusion_phoneme=confusion_phoneme,
        diagnostic=diagnostic["in_diagnostic"] or not targets,
    )

    exercise = selection["exercise"]
    if selection["generated"] is not None:
        generated = selection["generated"]
        new_id = db.insert_sentence(
            text=generated["text"],
            reference_ipa=generated["reference_ipa"],
            word_count=generated["word_count"],
            level_proxy=generated["level_proxy"],
            phoneme_counts=generated["phoneme_counts"],
            source=generated.get("source", "llm_generated"),
        )
        if new_id is not None:
            generated["id"] = new_id
            exercise = generated
        else:
            existing = db.get_sentence_by_text(generated["text"])
            if existing is not None:
                generated["id"] = existing["id"]
                exercise = generated

    if exercise is None:
        return {
            "assessment": assessment,
            "exercise": None,
            "error": "No exercises available. Run scripts/build_exercise_bank.py to populate the bank.",
        }

    confusion_hint = _confusion_hint_for(top_target, db.get_confusion_pairs(user_id))
    return {
        "assessment": assessment,
        "source_mode": selection["source_mode"],
        "exercise_type": exercise_type,
        "confusion_hint": confusion_hint,
        "target_phonemes": targets,
        "exercise": {
            "sentence_id": exercise["id"],
            "text": exercise["text"],
            "reference_ipa": exercise["reference_ipa"],
        },
    }


def provisional_assessment_from_metrics(metrics: Dict[str, float]) -> Dict[str, Any]:
    """Lightweight, honest assessment for a raw {phoneme: score} map.

    No recording/prompt evidence is available here, so this cannot claim an
    established level: weak/strong come straight from the provided scores and
    ``assessment_status`` is capped at ``provisional``.
    """
    from src.core.g2p.phoneme_vectors_professional import canonicalize_phoneme, is_assessable

    clean: Dict[str, float] = {}
    for phoneme, score in (metrics or {}).items():
        canon = canonicalize_phoneme(phoneme)
        numeric = float(score)
        if canon and is_assessable(canon) and math.isfinite(numeric):
            clean[canon] = max(0.0, min(1.0, numeric))

    weak = sorted(
        ({"phoneme": p, "mastery": round(s, 3), "lower_confidence_bound": round(s, 3)}
         for p, s in clean.items() if s <= assessment_mod.WEAK_MASTERY_THRESHOLD),
        key=lambda w: w["mastery"],
    )
    strong = sorted(p for p, s in clean.items() if s >= assessment_mod.STRONG_MASTERY_THRESHOLD)
    from src.core.g2p.phoneme_vectors_professional import ASSESSABLE_INVENTORY
    unknown = sorted(ASSESSABLE_INVENTORY - set(clean))

    if clean:
        mean = sum(clean.values()) / len(clean)
        score = round(100.0 * mean, 1)
        level = assessment_mod._level_from_score(score)
        status = "provisional"
    else:
        score = None
        level = "unknown"
        status = "insufficient_evidence"

    return {
        "pronunciation_score": score,
        "overall_level": level,
        "exercise_level": level,
        "borderline_levels": [],
        "level_decision": level,
        "level_decision_basis": "raw_mean_no_interval",
        "assessment_status": status,
        "inventory_coverage": round(len(clean) / max(len(ASSESSABLE_INVENTORY), 1), 3),
        "eligible_phoneme_count": len(clean),
        "tracked_phoneme_count": len(clean),
        "independent_recording_count": 0,
        "effective_recording_count": 0.0,
        "credible_interval": None,
        "interval_method": "none_stateless_metrics",
        "weak_phonemes": weak,
        "unknown_phonemes": unknown,
        "strong_phonemes": strong,
        "provisional": True,
        "assessment_source": "stateless_raw_metrics",
        "raw_stateless_metrics": True,
        "note": "Provisional level from finite supplied scores clamped to [0,1] (no evidence counts).",
    }


def metrics_for_user(user_name: str) -> Dict[str, float]:
    """Saved profile's per-phoneme decayed mastery as a plain score map."""
    user_row = db.get_user_by_name(user_name)
    if user_row is None:
        return {}
    now = datetime.now(timezone.utc)
    metrics = {}
    for phoneme, stat in load_profile_stats(user_row["id"]).items():
        metrics[phoneme] = mastery.posterior_mean(stat, now=now)
    return metrics
